#! /bin/bash

# copy CharlesGo to files folder, to be inserted in CharlinhOS build
mv /charles_go_build/CharlesGo /builds/gabriel-technologia/iot/charlinhos/files/opt/gabriel/bin

# untar CharlinhOS Image Builder
tar -xf /charlinhos* -C / && rm /charlinhos*.tar.xz

# build CharlinhOS
cd /charlinhos*
time make image PROFILE="hilink_hlk-7628n" FILES="/builds/gabriel-technologia/iot/charlinhos/files" PACKAGES="base-files bash busybox cJSON ca-bundle cgi-io coreutils coreutils-stty dnsmasq dropbear firewall4 fstools fwtool getrandom glib2 gpiod-tools hostapd-common htop ip-tiny ip6tables-nft ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-nft iw iwinfo jansson jq jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-aead kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-gcm kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-manager kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha256 kmod-gpio-button-hotplug kmod-hid kmod-hid-generic kmod-input-core kmod-input-evdev kmod-ip6tables kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipset kmod-ipt-raw kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-mac80211 kmod-mii kmod-mt76-core kmod-mt7603 kmod-nf-conntrack kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-ppp kmod-pppoe kmod-pppox kmod-slhc kmod-usb-core kmod-usb-ehci kmod-usb-hid kmod-usb-net kmod-usb-net-cdc-ether kmod-usb-net-cdc-mbim kmod-usb-net-cdc-ncm kmod-usb-net-qmi-wwan kmod-usb-net-rtl8152 kmod-usb-serial kmod-usb-serial-option kmod-usb-serial-wwan kmod-usb-wdm kmod-usb2 libattr libblobmsg-json libbz2 libc libcares libcurl libevdev libffi libgcc libgdbm libgpiod libipset libiptext-nft libiptext libiptext6 libiwinfo-data libiwinfo-lua libiwinfo libjson-c libjson-script liblua liblucihttp-lua liblucihttp liblzma libmbim libmnl libmosquitto-ssl libncurses libnftnl libnghttp2 libnl-tiny libopenssl-conf libopenssl libpcre libpthread libqmi libqrtr-glib libreadline librt libsqlite3 libssh libssh2 libstdcpp libubox libubus-lua libubus libuci libuclient libucode libudev-zero libusb-1.0 libustream-openssl libuuid libxtables logd lua luci luci-app-firewall luci-app-opkg luci-base luci-lib-base luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-qmi luci-ssl-openssl luci-theme-bootstrap minicom mtd netifd nftables-json odhcp6c odhcpd-ipv6only openssh-sftp-client openssl-util openwrt-keyring opkg ppp ppp-mod-pppoe procd procd-seccomp procd-ujail psmisc qmi-utils r8152-firmware rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns shadow-common shadow-su shadow-utils stm32flash sudo swconfig terminfo ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-ubus ucode-mod-uci uhttpd uhttpd-mod-ubus umbim uqmi urandom-seed urngd usb-modeswitch usbutils usign wireless-regdb wpad-basic-openssl wwan xtables-nft zlib -wpad-basic-wolfssl -libustream-wolfssl"

mkdir /output
mv /charlinhos*/bin/targets/ramips/mt76x8/*sysupgrade.bin /output/charlinhos-sysupgrade.bin