#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param command socketxp --config /opt/socketxp/config.json
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${threshold:-2} ${timeout:-5} ${retry:-0}
	procd_set_param name "SocketXp"
    procd_close_instance
}
